name: DEV Deployment

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nomanhassan9/frontend-app

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set version tag
        run: echo "VERSION=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build ONCE
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # Create version tag from same image
      - name: Tag Versioned Image
        run: |
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION

      # Push both tags
      - name: Push Docker Images
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION

      - name: Deploy to DEV EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USER }}
          key: ${{ secrets.EC2_DEV_KEY }}
          script: |
            docker pull nomanhassan9/frontend-app:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d \
              --name frontend \
              -p 80:80 \
              --restart always \
              nomanhassan9/frontend-app:latest
