name: PROD Deployment

on:
  workflow_run:
    workflows: ["DEV Deployment"]
    types:
      - completed

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: production   # manual approval required

    steps:
      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull nomanhassan9/frontend-app:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d \
              --name frontend \
              -p 80:80 \
              --restart always \
              nomanhassan9/frontend-app:latest
